import type { Agent, ExecutionLog, MonthlyYield } from '@/types/ai-orbit';

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agent-aapl',
    ticker: 'AAPL',
    companyName: 'Apple Inc.',
    status: 'ACTIVE',
    phase: 'CALL',
    riskProfile: 'BALANCED',
    capturedPremium: 1245.5,
    positionPl: 382.1,
    rawStockBasis: 187.32,
    totalCapturedPremiums: 6.85,
    sharesHeld: 100,
    position: {
      contracts: 1,
      strike: 195,
      expiration: '2026-08-21',
      dte: 14,
      premiumCollected: 142.0,
      underlyingPrice: 191.4,
    },
    targetDte: 21,
    createdAt: '2026-04-02',
  },
  {
    id: 'agent-tsla',
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    status: 'ACTIVE',
    phase: 'PUT',
    riskProfile: 'AGGRESSIVE',
    capturedPremium: 2110.25,
    positionPl: -145.6,
    rawStockBasis: 0,
    totalCapturedPremiums: 21.1,
    sharesHeld: 0,
    position: {
      contracts: 2,
      strike: 210,
      expiration: '2026-08-14',
      dte: 7,
      premiumCollected: 410.0,
      underlyingPrice: 214.2,
    },
    targetDte: 14,
    createdAt: '2026-03-18',
  },
  {
    id: 'agent-nvda',
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    status: 'PAUSED',
    phase: 'CALL',
    riskProfile: 'CONSERVATIVE',
    capturedPremium: 94.3,
    positionPl: 51.2,
    rawStockBasis: 118.6,
    totalCapturedPremiums: 0.94,
    sharesHeld: 100,
    position: {
      contracts: 1,
      strike: 130,
      expiration: '2026-09-18',
      dte: 42,
      premiumCollected: 61.0,
      underlyingPrice: 121.9,
    },
    targetDte: 30,
    createdAt: '2026-06-10',
  },
  {
    id: 'agent-msft',
    ticker: 'MSFT',
    companyName: 'Microsoft Corporation',
    status: 'ERROR',
    phase: 'PUT',
    riskProfile: 'BALANCED',
    capturedPremium: 0,
    positionPl: 0,
    rawStockBasis: 0,
    totalCapturedPremiums: 0,
    sharesHeld: 0,
    position: null,
    targetDte: 21,
    createdAt: '2026-07-29',
  },
];

export const MOCK_LOGS: ExecutionLog[] = [
  { id: 'log-1', timestamp: '2026-08-07T13:42:11Z', ticker: 'AAPL', level: 'FILL', message: 'Sold 1x AAPL 195C @ $1.42, expiring 2026-08-21.' },
  { id: 'log-2', timestamp: '2026-08-07T13:42:05Z', ticker: 'AAPL', level: 'ACCEPTED', message: 'Order accepted by broker: SELL_TO_OPEN 1x AAPL 195C.' },
  { id: 'log-3', timestamp: '2026-08-07T13:41:58Z', ticker: 'MSFT', level: 'REJECTED', message: 'Order rejected: insufficient buying power for CSP collateral.' },
  { id: 'log-4', timestamp: '2026-08-07T13:30:00Z', ticker: '—', level: 'CRON_POLL', message: 'Scheduled poll: evaluating 4 active agents for roll/close conditions.' },
  { id: 'log-5', timestamp: '2026-08-07T12:15:33Z', ticker: 'TSLA', level: 'FILL', message: 'Sold 2x TSLA 210P @ $2.05, expiring 2026-08-14.' },
  { id: 'log-6', timestamp: '2026-08-07T12:15:20Z', ticker: 'TSLA', level: 'ACCEPTED', message: 'Order accepted by broker: SELL_TO_OPEN 2x TSLA 210P.' },
  { id: 'log-7', timestamp: '2026-08-07T12:00:00Z', ticker: '—', level: 'CRON_POLL', message: 'Scheduled poll: evaluating 4 active agents for roll/close conditions.' },
  { id: 'log-8', timestamp: '2026-08-07T09:32:44Z', ticker: 'NVDA', level: 'REJECTED', message: 'Order rejected: agent paused by user before submission.' },
  { id: 'log-9', timestamp: '2026-08-06T15:02:19Z', ticker: 'AAPL', level: 'FILL', message: 'Bought to close 1x AAPL 190C @ $0.08 — expiring worthless, premium captured.' },
  { id: 'log-10', timestamp: '2026-08-06T09:30:01Z', ticker: '—', level: 'CRON_POLL', message: 'Market open poll: scanning fleet for new entry conditions.' },
];

export const MOCK_MONTHLY_YIELD: MonthlyYield[] = [
  { month: 'Feb', putPremium: 210, callPremium: 140 },
  { month: 'Mar', putPremium: 340, callPremium: 205 },
  { month: 'Apr', putPremium: 290, callPremium: 260 },
  { month: 'May', putPremium: 410, callPremium: 300 },
  { month: 'Jun', putPremium: 380, callPremium: 355 },
  { month: 'Jul', putPremium: 520, callPremium: 410 },
  { month: 'Aug', putPremium: 610, callPremium: 480 },
];

export const TOTAL_PREMIUM_CAPTURED = 3450.0;
